### ISSUE TITLE
I can't specify the version to install a package on OPM

### ISSUE THREAD

**Issue by hybridsong** [openresty/opm#49]
➜  bin sudo ./opm get bungle/lua-resty-template=1.9
Fetching bungle/lua-resty-template = 1.9
ERROR: unexpected server response status code for URL "https://opm.openresty.org/api/pkg/fetch?account=bungle&name=lua-resty-template&op=eq&version=1.9": 504
➜  bin sudo ./opm get bungle/lua-resty-template=v1.9
Fetching bungle/lua-resty-template = v1.9
ERROR: unexpected server response status code for URL "https://opm.openresty.org/api/pkg/fetch?account=bungle&name=lua-resty-template&op=eq&version=v1.9": 504

Could you tell me how to solve this? Thank you.

**Comment by agentzh** [comment]
@hybridsong I tried your command on my side and it works as expected:

```
$ sudo opm get bungle/lua-resty-template=1.9
* Fetching bungle/lua-resty-template = 1.9
  Downloading https://opm.openresty.org/api/pkg/tarball/bungle/lua-resty-template-1.9.opm.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 32271  100 32271    0     0  28578      0  0:00:01  0:00:01 --:--:-- 28558
Package bungle/lua-resty-template 1.9 installed successfully under /usr/local/openresty/site/ .
```

The 504 error looks like a CDN issue. The opm.openresty.org site is using YunFan's CDN network in mainland China. We're migrating to our own CDN network soon so that we can track such issues more easily and more quickly. Thanks for the report.
