### ISSUE TITLE
Better documentation on requires for luajit, nginx, openresty, ngx_http_module

### ISSUE THREAD

**Issue by bungle** [openresty/opm#6]
#The requires:
https://github.com/openresty/opm#requires

lists `luajit`, `nginx`, openresty`, and `ngx_http_module` as special dependency names, but doesn't clearly define their meaning. Also it is strange to have `ngx_http_module`, but not to have basically all the other modules? Is `ngx_http_module` a reference to this: https://github.com/openresty/lua-nginx-module (what about the stream module?). Wouldn't `luajit`+`nginx` / `luajit`+`openresty` do the same? And should we have `lua` there as well?

Now the meaning of these should be documented (these are just examples):

* `lua` = Needs Lua, and works also with LuaJIT
* `luajit` = Needs LuaJIT and doesn't work with PUC-Lua
* `nginx` = Needs nginx (referring to official nginx reference packages supplied from nginx.org with default configuration)
* `openresty` = Needs official OpenResty bundle (with default configuration) - what is the definition of `openresty` is vague as you can always build your own with Nginx + modules + resty libraries.
* `ngx_http_module` = Needs `ngx_http_module` (not sure why it is here specifically, this could lead to us having to add every other `ngx_*` module here as well?

Now the requires line is AND-type, am I correct? But with the current set of these requires, you might end up needing OR as well.

So the definition and meaning of these should be more clean to the package writer. Now I kinda almost know what they mean, but a lot of questions arises as well. Also adding a lot of these special dependency names adds complexity, and frustration.

**Comment by agentzh** [comment]
@bungle Well, opm is only (officially) expected to work properly with OpenResty, not really self-made nginx + ngx_lua (though knowledgeable users can make that work, but it's not officially supported).

I've added more docs for those special dependency names. BTW, it is `ngx_http_lua` instead of `ngx_http_module`.

Yes, all the deps are AND'd together.

The `openresty` dep is just for convenience. You do not have to use it. And when `openresty >= version` is specified, there is no need to specify `nginx >= version` or `luajit >= version` or `ngx_http_lua >= version' at all. Usually the package author can just specify the `openresty` dep.

We could add an `ngx_stream_lua` dep in the future as well.
