### ISSUE TITLE
Additional root files for document collection 

### ISSUE THREAD

**Issue by bungle** [openresty/opm#8]
Should the list that currently has these:

* `README.md`, `README.markdown`, or `README.pod`
* `COPYING`
* `COPYRIGHT`
* `Changes.md`, `Changes.markdown`, or `Changes.pod`

Also have

* `README`
* `CHANGES`

Added?

**Comment by agentzh** [comment]
@bungle No, I don't want to since I hope we can encourage (or enforce) the user to write these important docs in a formatting language like Markdown and POD. This is because

1. We want these docs to be indexed by the `restydoc` tool.
2. We want to (eventually) render these files as nice-looking HTML pages on the opm.openresty.org website.

**Comment by bungle** [comment]
Ok, I have nothing against it.

**Comment by bungle** [comment]
@agentzh,

Is there by the way a suggested way that we should follow when writing, e.g. CHANGES.md?

**Comment by agentzh** [comment]
@bungle Better like this:

https://raw.githubusercontent.com/openresty/openresty.org/master/v2/en/changelog-1011002.md
